server:
  port: 10086
logging:
  level:
    xyz.thuray.geniuslens: debug
    org.mybatis: debug
spring:
  datasource:
    url: jdbc:postgresql://10.10.10.145:5432/genius_lens?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: seal
    password: 0nlin@seal
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: 10.10.10.145:9092
  data:
    redis:
      host: 10.10.10.145
      port: 6379
      database: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
retrofit:
  # 全局日志打印配置
  global-log:
    # 启用日志打印
    enable: true
    # 全局日志打印级别
    log-level: debug
    # 全局日志打印策略
    log-strategy: basic
    # 是否聚合打印请求日志
    aggregate: true

  # 全局超时时间配置
  global-timeout:
    # 全局读取超时时间
    read-timeout-ms: 100000
    # 全局写入超时时间
    write-timeout-ms: 100000
    # 全局连接超时时间
    connect-timeout-ms: 100000
    # 全局完整调用超时时间
    call-timeout-ms: 0
cache:
  impl: local
